### ISSUE TITLE
os: getcwd does not work on bare-metal

### ISSUE THREAD

**Issue by stlehmann** [pfalcon/micropython-lib#15]
`getcwd` does not work on 'bare-metal' ports of Micropython. This is in fact a major bug as `getcwd` is used by mfpshell. When installing `os` package on a 'bare-metal' port like ESP8266 or ESP32 the board will no longer be accessible via mpfshell.

**Comment by pfalcon** [comment]
Thanks for the report and investigating what causes the trouble. Well, if you followed the links I posted in https://github.com/pfalcon/micropython-lib/pull/12, it should be obvious how to fix that (https://github.com/pfalcon/micropython-lib/commit/7af606cdedcf16a80da0c9bd2cbde2384df9700d again). I encourage you to make a fix, test it, and then submit as a PR. If not, well, I'll get to it (but it will be longer ;-) ).

**Comment by stlehmann** [comment]
The way you did it on https://github.com/pfalcon/micropython-lib/commit/7af606cdedcf16a80da0c9bd2cbde2384df9700d would be my choice as well. I needed some time to have a closer look in `os`. I'll get to it.
