### ISSUE TITLE
logging: Implement custom formatting

### ISSUE THREAD

**Issue by stlehmann** [pfalcon/micropython-lib#21]
Like discussed before it would be great to allow custom formatting by the model of CPython. This can be done by passing a Formatter object that contains the necessary format information to a handler or by passing a `format` parameter to `basicConfig()`.

I'm already on this issue and opened it to keep track on it and discuss some details.

**Comment by pfalcon** [comment]
> or by passing a format parameter to basicConfig().

May I suggest starting with that? And likewise, start with implementing just a little few of fields there.

**Comment by stlehmann** [comment]
I was thinking of adding a bit of documentation in a Readme.md to show how to use the package and where it differs from the CPython version. Would you approve that?

**Comment by pfalcon** [comment]
Should be `README.rst`, as reST is the default markup used in Python. See e.g. uasyncio/ for example. Otherwise sure, great idea!

And yeah, I wanted to ask if this ticket should be kept open or can be closed now.
